
select * from customer limit 15 
select current_user, now()

--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from customer group by gender

--Q2. Which customers used a discount but still spent more
--than the average purchase amount? 
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount 
>= (select AVG(purchase_amount)from customer)

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2)
from customer GROUP BY item_purchased  ORDER BY round(avg(review_rating::numeric),2) desc limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type ,round(avg(purchase_amount),2) from customer 
where  shipping_type in ('Express','Standard') group by shipping_type

select * from customer limit 15 
--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status, round(avg(purchase_amount),2), 
sum(purchase_amount) as total_revenue from customer 
group by subscription_status order by  total_revenue 

--Q6. Which 5 products have the highest percentage of purchases with 
--discounts applied? 100*(sum of all 1s)/all total rows 
select item_purchased, round(100* sum(case when discount_Applied = 'Yes' 
		then 1 else 0 end) /count(*),2) as percentage 
from customer group by item_purchased 
order by percentage  desc limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as(
	select customer_id,previous_purchases,
	case
		when previous_purchases = 1 then 'new'
		when previous_purchases between 2 and 10 then 'returning'
		else 'loyal'
	    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


--q8 what are the three most purchased products within each category?
with item_counts as(
select category, item_purchased,
count(customer_id) as total_customers,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from customer
group by category, item_purchased)
select category ,item_purchased,total_customers,item_rank
from item_counts
where item_rank <=3



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) 
--also likely to subscribe?
select subscription_status,
count (customer_id) as total_buyers
from customer
where previous_purchases>5
group by subscription_status 
order by total_buyers

--Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;




